// Typed IPC contract mirrored from the Rust core via `ts-rs`.
// Regenerate with: `cargo test -p agentic-core --features ts-export`.
// Do not hand-edit files under `generated/`.

export type { AdapterStatus } from "./generated/AdapterStatus";
export type { CapabilityItem } from "./generated/CapabilityItem";
export type { CapabilityKind } from "./generated/CapabilityKind";
export type { ApplyError } from "./generated/ApplyError";
export type { ApplyProgressEvent } from "./generated/ApplyProgressEvent";
export type { ApplyResult } from "./generated/ApplyResult";
export type { ApplySuiteResult } from "./generated/ApplySuiteResult";
export type { EditorPref } from "./generated/EditorPref";
export type { ScaffoldMode } from "./generated/ScaffoldMode";
export type { ScaffoldResult } from "./generated/ScaffoldResult";
export type { SuiteDefinition } from "./generated/SuiteDefinition";
export type { SuiteValidationResult } from "./generated/SuiteValidationResult";
export type { SuiteStoreChangedEvent } from "./generated/SuiteStoreChangedEvent";
export type { WorkspaceApply } from "./generated/WorkspaceApply";
export type { WorkspaceTarget } from "./generated/WorkspaceTarget";
export type { WorkspaceTargetsState } from "./generated/WorkspaceTargetsState";
export type { WorkspacePatchResult } from "./generated/WorkspacePatchResult";
export type { HookSyncError } from "./generated/HookSyncError";
export type { HookSyncOutcome } from "./generated/HookSyncOutcome";
export type { SyncHooksResult } from "./generated/SyncHooksResult";
export type { InspectResult } from "./generated/InspectResult";
export type { IpcError } from "./generated/IpcError";
export type { LinkState } from "./generated/LinkState";
export type { OperationKind } from "./generated/OperationKind";
export type { PlannedOperation } from "./generated/PlannedOperation";
export type { RuleSyncError } from "./generated/RuleSyncError";
export type { RuleSyncOutcome } from "./generated/RuleSyncOutcome";
export type { SyncRulesResult } from "./generated/SyncRulesResult";
export type { ScanError } from "./generated/ScanError";
export type { ScanResult } from "./generated/ScanResult";
export type { Settings } from "./generated/Settings";
export type { SourceConfig } from "./generated/SourceConfig";
export type { ToolCapabilityState } from "./generated/ToolCapabilityState";
export type { ToolId } from "./generated/ToolId";
export type { ToolSettings } from "./generated/ToolSettings";
export type { ToolsSettings } from "./generated/ToolsSettings";
